/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NButton {
        "disabled"?: boolean;
        "size"?: 'default' | 'sm' | 'lg';
        "type"?: 'button' | 'submit' | 'reset';
        "variant"?: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
    }
}
declare global {
    interface HTMLNButtonElement extends Components.NButton, HTMLStencilElement {
    }
    var HTMLNButtonElement: {
        prototype: HTMLNButtonElement;
        new (): HTMLNButtonElement;
    };
    interface HTMLElementTagNameMap {
        "n-button": HTMLNButtonElement;
    }
}
declare namespace LocalJSX {
    interface NButton {
        "disabled"?: boolean;
        "size"?: 'default' | 'sm' | 'lg';
        "type"?: 'button' | 'submit' | 'reset';
        "variant"?: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
    }
    interface IntrinsicElements {
        "n-button": NButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "n-button": LocalJSX.NButton & JSXBase.HTMLAttributes<HTMLNButtonElement>;
        }
    }
}
